Upgrade to Rails 6.1
The master branch of actionpack-action_caching has Rails 6.1 support,
but a new version of the gem hasn't been released yet, so we need to
source it from GitHub.

Without the addition of `require "active_support/core_ext/integer/time"`
to `application.rb`, we get this error:

    An error occurred while loading ./spec/models/user_spec.rb.
    Failure/Error: require File.expand_path('../../config/environment', __FILE__)

    NoMethodError:
      undefined method `day' for 1:Integer